version: '3.3'

services:
  core:
    image: core
    build: .
    env_file:
      - .env
    volumes:
      - bull_file_data:/var/lib/bull/uploads
    ports:
      - 4000:4000
    restart: unless-stopped

  bull_postgres:
    image: postgres:10
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - bull_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  bull_postgres_data:
  bull_file_data:

networks:
  default:
    external:
      name: bull
