version: '3.3'

services:
  core:
    image: core
    build: .
    env_file:
      - .env
    volumes:
      - file_data:/var/lib/core/uploads
    ports:
      - 4000:4000
    restart: unless-stopped

  postgres:
    image: postgres:10
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  file_data:

networks:
  default:
    external:
      name: bull
